PACKAGE_NAME="fake_inotify"
PACKAGE_VERSION="1.0"
CLEAN="make clean"
MAKE[0]="make all"
BUILT_MODULE_NAME[0]="fake_inotify"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc/"
AUTOINSTALL="yes"
POST_INSTALL="postinst"
